controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
dql:
    path: /dql
    controller: App\Controller\ProduitController::dql
    methods: ['POST']

